13-Jan-21 13:11:29 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 26, in gold_choice_message
    data_from_db = get_data()
  File "/home/let/PycharmProjects/t_gold_price/bot.py", line 10, in get_data
    modified_date = datetime.datetime.fromtimestamp(os.path.getmtime(DB_FILENAME))
  File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'datafile'
13-Jan-21 13:11:33 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-13' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 26, in gold_choice_message
    data_from_db = get_data()
  File "/home/let/PycharmProjects/t_gold_price/bot.py", line 10, in get_data
    modified_date = datetime.datetime.fromtimestamp(os.path.getmtime(DB_FILENAME))
  File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'datafile'
13-Jan-21 13:11:35 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 26, in gold_choice_message
    data_from_db = get_data()
  File "/home/let/PycharmProjects/t_gold_price/bot.py", line 10, in get_data
    modified_date = datetime.datetime.fromtimestamp(os.path.getmtime(DB_FILENAME))
  File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'datafile'
13-Jan-21 13:11:37 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-21' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 26, in gold_choice_message
    data_from_db = get_data()
  File "/home/let/PycharmProjects/t_gold_price/bot.py", line 10, in get_data
    modified_date = datetime.datetime.fromtimestamp(os.path.getmtime(DB_FILENAME))
  File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'datafile'
13-Jan-21 13:11:41 - aiogram - WARNING - Goodbye!
13-Jan-21 13:29:10 - aiogram - WARNING - Goodbye!
14-Jan-21 00:10:26 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=TypeError("generate_keyboard() missing 1 required positional argument: 'choice'")>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 19, in start_message
    reply_markup=generate_keyboard()
TypeError: generate_keyboard() missing 1 required positional argument: 'choice'
14-Jan-21 00:10:39 - aiogram - WARNING - Goodbye!
14-Jan-21 00:11:48 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BadRequest("Can't parse reply keyboard markup json object")>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 13, in start_message
    await message.answer(f"Цена одного грамма чистого золота 999 пробы (24K):\n"
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/types/message.py", line 339, in answer
    return await self.bot.send_message(
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse reply keyboard markup json object
14-Jan-21 00:11:56 - aiogram - WARNING - Goodbye!
14-Jan-21 00:14:50 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 19, in start_message
    reply_markup=generate_keyboard(999)
  File "/home/let/PycharmProjects/t_gold_price/keyboards/inline/gold_keyboard.py", line 14, in generate_keyboard
    return json.loads(f'gold_choice = InlineKeyboardMarkup(inline_keyboard={new_keyboard})')
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
14-Jan-21 00:14:54 - aiogram - WARNING - Goodbye!
14-Jan-21 00:17:01 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=ObjectExpectedAsReplyMarkup('Object expected as reply markup')>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 13, in start_message
    await message.answer(f"Цена одного грамма чистого золота 999 пробы (24K):\n"
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/types/message.py", line 339, in answer
    return await self.bot.send_message(
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ObjectExpectedAsReplyMarkup: Object expected as reply markup
14-Jan-21 00:17:06 - aiogram - WARNING - Goodbye!
14-Jan-21 00:36:29 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BadRequest("Can't parse reply keyboard markup json object")>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 13, in start_message
    await message.answer(f"Цена одного грамма чистого золота 999 пробы (24K):\n"
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/types/message.py", line 339, in answer
    return await self.bot.send_message(
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse reply keyboard markup json object
14-Jan-21 00:36:34 - aiogram - WARNING - Goodbye!
14-Jan-21 08:59:27 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BadRequest("Can't parse inline keyboard button: inlinekeyboardbutton must be an object")>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 13, in start_message
    await message.answer(f"Цена одного грамма чистого золота 999 пробы (24K):\n"
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/types/message.py", line 339, in answer
    return await self.bot.send_message(
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
14-Jan-21 09:01:12 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BadRequest("Can't parse inline keyboard button: inlinekeyboardbutton must be an object")>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 13, in start_message
    await message.answer(f"Цена одного грамма чистого золота 999 пробы (24K):\n"
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/types/message.py", line 339, in answer
    return await self.bot.send_message(
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
14-Jan-21 09:01:18 - aiogram - WARNING - Goodbye!
14-Jan-21 09:06:02 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_polling_updates() done, defined at /home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BadRequest("Can't parse inline keyboard button: inlinekeyboardbutton must be an object")>
Traceback (most recent call last):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/let/PycharmProjects/t_gold_price/handlers/main_handlers.py", line 13, in start_message
    await message.answer(f"Цена одного грамма чистого золота 999 пробы (24K):\n"
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/types/message.py", line 339, in answer
    return await self.bot.send_message(
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/let/PycharmProjects/t_gold_price/venv/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
14-Jan-21 09:07:30 - aiogram - WARNING - Goodbye!
14-Jan-21 09:42:26 - aiogram - WARNING - Goodbye!
14-Jan-21 09:45:19 - aiogram - WARNING - Goodbye!
14-Jan-21 09:45:33 - aiogram - WARNING - Goodbye!
14-Jan-21 09:46:44 - aiogram - WARNING - Goodbye!
14-Jan-21 09:49:27 - aiogram - WARNING - Goodbye!
14-Jan-21 09:50:35 - aiogram - WARNING - Goodbye!
14-Jan-21 09:51:28 - aiogram - WARNING - Goodbye!
14-Jan-21 10:04:47 - aiogram - WARNING - Goodbye!
14-Jan-21 10:07:35 - aiogram - WARNING - Goodbye!
14-Jan-21 10:09:42 - aiogram - WARNING - Goodbye!
